[package]
name = "lolch_bot_rust"
version = "0.1.0"
edition = "2021"

[dependencies]
mysql = "25.0.1"
regex = "1.11.1"
reqwest = { version = "0.12.9", features = ["blocking", "json"] }
scraper = "0.22.0"
